version: "3"
services:
 postgres:
   build: postgres
   healthcheck:
     test: echo "select * from spatial_ref_sys LIMIT 1;" | psql -d test_database -U adnybody
     interval: 10s
     timeout: 10s
     retries: 5
 redis:
   image: redis:3.2.9
 windshaft:
   image: akvo/akvo-maps
   volumes:
      - ./windshaft/config/dev:/config
 tests:
   build:
     context: ./end-to-end-tests
     dockerfile: Dockerfile
   volumes:
      - ./end-to-end-tests:/tests
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
   depends_on:
      - redis
      - windshaft
      - postgres:
          condition: service_healthy
   command: ["true"]