version: "3"

services:
 postgres:
   build: postgres
   expose:
     - 5432
   volumes:
     - pg-data:/var/lib/postgresql/data
 redis:
   image: redis:3.2.9
 windshaft:
   image: "akvo/akvo-maps:${IMAGE_TAG}"
   volumes:
      - ./windshaft/config/dev:/config
      - pg-data:/pg-certs:ro
   environment:
     - PGSSLROOTCERT=/pg-certs/server.crt
     - ENCRYPTION_KEY=cdascmdsaklfmjwqe
   depends_on:
     - postgres
 windshaft2:
   image: "akvo/akvo-maps:${IMAGE_TAG}"
   volumes:
      - ./windshaft/config/dev:/config
      - pg-data:/pg-certs:ro
   environment:
     - PGSSLROOTCERT=/pg-certs/server.crt
     - ENCRYPTION_KEY=cdascmdsaklfmjwqe
   depends_on:
     - postgres
 tests:
   image: clojure:lein-2.7.1
   volumes:
      - ./end-to-end-tests:/tests
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
      - pg-data:/pg-certs:ro
   working_dir: /tests
   environment:
     - ENCRYPTION_KEY=cdascmdsaklfmjwqe
   depends_on:
      - redis
      - windshaft
      - windshaft2
      - postgres
   command: "true"
volumes:
  pg-data:
