version: "3"
services:
 postgres:
   build: postgres
   expose:
     - 5432
 redis:
   image: redis:3.2.9
 windshaft:
   image: "akvo/akvo-maps:${IMAGE_TAG}"
   volumes:
      - ./windshaft/config/dev:/config
      - ./postgres/provision:/pg-certs
   environment:
     - PGSSLROOTCERT=/pg-certs/server.crt
     - ENCRYPTION_KEY=cdascmdsaklfmjwqe
 windshaft2:
   image: "akvo/akvo-maps:${IMAGE_TAG}"
   volumes:
      - ./windshaft/config/dev:/config
      - ./postgres/provision:/pg-certs
   environment:
     - PGSSLROOTCERT=/pg-certs/server.crt
     - ENCRYPTION_KEY=cdascmdsaklfmjwqe
 tests:
   build:
     context: ./end-to-end-tests
     dockerfile: Dockerfile
   volumes:
      - ./end-to-end-tests:/tests
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
      - ./postgres/provision:/pg-certs
   environment:
     - ENCRYPTION_KEY=cdascmdsaklfmjwqe
   depends_on:
      - redis
      - windshaft
      - windshaft2
      - postgres
   command: "true"
