version: "3"
services:
 postgres:
   build: postgres
   ports:
    - "5432:5432"
   volumes:
      - ./postgres:/here
 redis:
   image: redis:3.2.9
 windshaft:
   build:
     context: ./windshaft
     dockerfile: Dockerfile
   environment:
     - NODE_HEAPDUMP_OPTIONS=nosignal
     - NODE_ENV=development
     - PGSSLROOTCERT=/pg-certs/server.crt
     - ENCRYPTION_KEY=asdfklmasclkmadslaqwewqe
   volumes:
      - ./windshaft/server:/tiler
      - ./windshaft/config/dev:/config
      - /tiler/node_modules
      - ./postgres/provision:/pg-certs
   ports:
      # debug port
      - "9229:9229"
      # http port
      - "4000:4000"
 windshaft2:
   build:
     context: ./windshaft
     dockerfile: Dockerfile
   environment:
     - NODE_ENV=development
     - PGSSLROOTCERT=/pg-certs/server.crt
     - ENCRYPTION_KEY=asdfklmasclkmadslaqwewqe
   volumes:
      - ./windshaft/server:/tiler
      - ./windshaft/config/dev:/config
      - /tiler/node_modules
      - ./postgres/provision:/pg-certs
   ports:
      # http port
      - "4001:4001"
 tests:
   build:
     context: ./end-to-end-tests
     dockerfile: Dockerfile
   environment:
      - ENCRYPTION_KEY=asdfklmasclkmadslaqwewqe
   volumes:
      - ./end-to-end-tests:/tests
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
      - ./postgres/provision:/pg-certs
   ports:
      # REPL
      - "47481:47480"
# statsd-server:
#    image: hopsoft/graphite-statsd
#    expose:
#          - "8125"
#    ports:
#       - 8550:80