version: "3"
services:
 postgres:
   build: postgres
   ports:
    - "5432:5432"
 redis:
   image: redis:3.2.9
 windshaft:
   build:
     context: ./windshaft
     dockerfile: Dockerfile
   environment:
     - NODE_HEAPDUMP_OPTIONS=nosignal
     - NODE_ENV=development
   volumes:
      - ./windshaft/server:/tiler
      - ./windshaft/config/dev:/config
      - /tiler/node_modules
   ports:
      - "9229:9229"
      - "4000:4000"
 windshaft2:
   build:
     context: ./windshaft
     dockerfile: Dockerfile
   environment:
     - NODE_ENV=development
   volumes:
      - ./windshaft/server:/tiler
      - ./windshaft/config/dev:/config
      - /tiler/node_modules
 tests:
   build:
     context: ./end-to-end-tests
     dockerfile: Dockerfile
   volumes:
      - ./end-to-end-tests:/tests
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
   ports:
      - "47481:47480"
# statsd-server:
#    image: hopsoft/graphite-statsd
#    expose:
#          - "8125"
#    ports:
#       - 8550:80