version: "3"
services:
 postgres:
   build: postgres
   ports:
     - "5432:5432"
   volumes:
     - pg-data:/var/lib/postgresql/data
 redis:
   image: redis:3.2.9
 windshaft:
   build:
     context: ./windshaft
     dockerfile: Dockerfile
   environment:
     - NODE_HEAPDUMP_OPTIONS=nosignal
     - NODE_ENV=development
     - PGSSLROOTCERT=/pg-certs/server.crt
     - ENCRYPTION_KEY=asdfklmasclkmadslaqwewqe
   volumes:
      - ./windshaft/server:/tiler
      - ./windshaft/config/dev:/config
      - /tiler/node_modules
      - pg-data:/pg-certs:ro
   ports:
      # debug port
      - "9229:9229"
      # http port
      - "4000:4000"
 windshaft2:
   build:
     context: ./windshaft
     dockerfile: Dockerfile
   environment:
     - NODE_ENV=development
     - PGSSLROOTCERT=/pg-certs/server.crt
     - ENCRYPTION_KEY=asdfklmasclkmadslaqwewqe
   volumes:
      - ./windshaft/server:/tiler
      - ./windshaft/config/dev:/config
      - /tiler/node_modules
      - pg-data:/pg-certs:ro
   ports:
      # http port
      - "4001:4001"
 tests:
   image: clojure:lein-2.7.1
   environment:
      - ENCRYPTION_KEY=asdfklmasclkmadslaqwewqe
   volumes:
      - ./end-to-end-tests:/tests
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
      - pg-data:/pg-certs:ro
   working_dir: /tests
   command: /tests/import-and-run.sh
   ports:
     - "47480:47480"
 statsd:
   build: statsd-to-prometheus
   volumes:
     - ./statsd-to-prometheus:/config
   ports:
     - "9102:9102"
   expose:
     - 9125
volumes:
  pg-data:
